### PR TITLE
Added gradle task for each deployment

### PR DESCRIPTION
**Pull request by Ovadia-B**

### CODE REVIEW

**Review by komu — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!

You didn't provide any context, so I'll have to guess, but it seems that the motivation behind this is to get listing of tasks (for IDE integration etc), but this doesn't change the actual behaviour? So, you'd still say `deployFoo`, but that task would be pre-created instead of being created on demand by `DeployRule`?

I'm a bit on the fence about this. On the other hand, if you have 3 environments, it's probably nice to get the tasks listed explicitly. Then again, if you have 30, perhaps having a rule is better. Task rules are also consistent with how Gradle itself handles similar things. But I guess most people have relatively few environments and this would improve their life, so I guess I'm willing to merge this.

However, before merging it would probably be a good strip away the old functionality. Right before your new code, there's registration for the old task rule:

```java
project.getTasks().addRule(new DeployRule(deployments, project, beanstalk));
```

Since the new code creates the tasks automatically, the rule is no longer needed: both the registration and `DeployRule`-class should be stripped.

Finally, the existing code has 4 space indents, the new code seems to use tabs, but even accounting for that, the indentation seems quite random.

So I'm prepared to merge this if this gets clean up first.

**Comment by Ovadia-B** [comment]
Yes, You are correct.
This will create a list of tasks in the IDE, for me it is very comfortable just to click on the task (or even assign a keyboard shortcut) instead of typing it.

**Comment by komu** [comment]
Sounds good. I think the benefits outweight the drawbacks, so I'll merge this and make a release once this is cleaned.

**Comment by Ovadia-B** [comment]
I have cleaned the code. 
If you can remove the .idea folder and add it to the .gitignore it will be more easy to open the project in the IDE.

**Comment by komu** [comment]
Thanks!

I just published `0.2.0` with these changes.

**Pull request merged**
